"""
Manual smoke test for the legacy ``screen_ai_pdf_parser`` compatibility module.

Usage:
    python test_pdf_parser.py [pdf_file_path]
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from screen_ai_pdf_parser import ChromeScreenAI, image_to_text, pdf_to_markdown


def print_section(title: str) -> None:
    print(f"\n{'=' * 50}")
    print(f"  {title}")
    print("=" * 50)


def check_dependencies() -> bool:
    print_section("Dependency Check")

    try:
        import fitz  # noqa: F401
        print("[OK] PyMuPDF is installed")
        return True
    except ImportError:
        print("[FAIL] PyMuPDF is not installed")
        print("Install it with: pip install pymupdf")
        return False


def check_screen_ai() -> bool:
    print_section("Chrome Screen AI")

    engine = ChromeScreenAI()
    if engine.ok:
        print("[OK] Chrome Screen AI DLL loaded")
        print(f"Max image dimension: {engine.max_dimension}")
        return True

    print("[INFO] Chrome Screen AI is unavailable")
    print("Image OCR and scanned-PDF OCR will be skipped")
    return False


def create_demo_pdf(path: str = "demo_test.pdf") -> str | None:
    print_section("Create Demo PDF")
    print(f"Target file: {path}")

    try:
        import fitz

        doc = fitz.open()

        page = doc.new_page()
        page.insert_text(
            (50, 50),
            "Chrome OCR Demo Document\n\n"
            "This PDF is generated by the repository smoke test.\n\n"
            "Main checks:\n"
            "1. Text-layer PDF extraction\n"
            "2. Basic page handling\n"
            "3. Legacy compatibility wrapper\n\n"
            "Generated by: test_pdf_parser.py",
            fontsize=12,
            fontname="helvetica",
        )

        page = doc.new_page()
        page.insert_text(
            (50, 50),
            "Second page content\n\n"
            "The quick brown fox jumps over the lazy dog.\n"
            "Numbers: 0 1 2 3 4 5 6 7 8 9\n"
            "This page confirms multi-page extraction.",
            fontsize=12,
            fontname="helvetica",
        )

        doc.save(path)
        doc.close()

        print(f"[OK] Demo PDF created: {path}")
        return path
    except Exception as exc:
        print(f"[FAIL] Could not create the demo PDF: {exc}")
        return None


def run_pdf_markdown_check(pdf_path: str) -> str | None:
    print_section(f"PDF to Markdown: {pdf_path}")

    if not os.path.exists(pdf_path):
        print(f"[FAIL] File does not exist: {pdf_path}")
        return None

    try:
        markdown = pdf_to_markdown(pdf_path)
        print("[OK] Markdown extraction succeeded")
        print(f"Character count: {len(markdown)}")
        print("Preview:")
        preview = markdown[:300] + ("..." if len(markdown) > 300 else "")
        for line in preview.splitlines()[:10]:
            print(f"  {line}")
        return markdown
    except Exception as exc:
        print(f"[FAIL] PDF extraction failed: {exc}")
        return None


def run_image_ocr_check() -> None:
    print_section("Image OCR")

    engine = ChromeScreenAI()
    if not engine.ok:
        print("[SKIP] Chrome Screen AI is not available")
        return

    try:
        from PIL import Image, ImageDraw, ImageFont

        img = Image.new("RGB", (600, 160), "white")
        draw = ImageDraw.Draw(img)
        try:
            font = ImageFont.truetype("arial.ttf", 32)
        except OSError:
            font = ImageFont.load_default()

        draw.text((20, 20), "Hello Chrome OCR", fill="black", font=font)
        draw.text((20, 70), "Legacy wrapper smoke test", fill="black", font=font)

        text = image_to_text(img, engine=engine)
        print("[OK] Image OCR completed")
        print("Preview:")
        for line in text.splitlines()[:10]:
            print(f"  {line}")
    except Exception as exc:
        print(f"[FAIL] Image OCR failed: {exc}")


def main() -> None:
    print("\n" + "=" * 50)
    print("  Legacy Compatibility Smoke Test")
    print("=" * 50)

    if not check_dependencies():
        return

    check_screen_ai()

    pdf_path = sys.argv[1] if len(sys.argv) > 1 else None
    if pdf_path and not os.path.exists(pdf_path):
        print(f"\n[FAIL] The specified PDF does not exist: {pdf_path}")
        pdf_path = None

    if pdf_path is None:
        pdf_path = create_demo_pdf()

    if not pdf_path:
        print("\n[FAIL] No PDF is available for testing")
        return

    markdown = run_pdf_markdown_check(pdf_path)
    if markdown is None:
        return

    run_image_ocr_check()

    print_section("Done")
    print("[OK] Smoke test completed")
    print(f"PDF source: {pdf_path}")


if __name__ == "__main__":
    main()
